image: python:2.7

stages:
 - test

before_script:
  - "pip install -U platformio"

job:
  stage: test
  script: "platformio ci --board=heltec_wifi_lora_32"
  variables: {PLATFORMIO_CI_SRC: "Turpial/src/Turpial.ino"}
